### PR TITLE
Add template functionality to enable custom HTML formatting of words in ...

### PR DESCRIPTION
**Pull request by thinkjones**
...tag clouds.  I needed to add icons with some of my tag words, using the post alter function ended up with some bad word wrapping, so I added a tempalte functionality where you can set the HTML directly.

### CODE REVIEW

**Comment by mistic100** [comment]
Why don't just replace "text" by "html" on line 328 and manage your template one level up ?

I would prefer this over adding an option on jQCloud (if I understand your usage, `template` is for example an underscore template, and `text` is an object)

**Comment by mistic100** [comment]
and please don't push "dist" (amend your last commit and do a force push)

**Comment by thinkjones** [comment]
Changing text to html on lines 325, 328, imho would be a breaking change.  Some people maybe relying on the text being encoded.  I think it's safer and more customizable to offer a template function for people to amend the tag anyway they want.  This is similar to how Kendo works - http://docs.telerik.com/kendo-ui/api/javascript/ui/combobox#configuration-template.

**Comment by mistic100** [comment]
>  Some people maybe relying on the text being encoded.

very unlikely... who would want < and > showing up ?
And honestly I don't mind breaking changes, I'll bump to 2.1 and it's ok

**Comment by mistic100** [comment]
Kendo uses a global template, it makes more sense that a template for each word, which is just like directly provide HTML

**Comment by thinkjones** [comment]
>very unlikely... who would want < and > showing up ?

Anybody that would want that functionality?  Why restrict them?  There's probably a reason jQuery provides .text and .html because it doesn't want to dictate what method you should use.

> Kendo uses a global template ...
Agree this would work better on the options object.

**Comment by mistic100** [comment]
I'm not building a generic usage library, I'm building a plugin which I try to keep as simple as possible. Keeping a option (I talk about "text", allowing HTML is great) for 0.05% of users is a nonsense.

If you move the template option, un-commit "dist" and squash your commits I'll merge though.

**Comment by mistic100** [comment]
Well sorry to bother you.

What is funny is that if someone had raised an issue saying "hey you use text instead of html and I can't put icons on my tags" I would have made the change straight away and nobody would have complained.

I'll reuse your idea though.

**Comment by thinkjones** [comment]
I am making the change at the moment.  New pull request coming shortly.

**Pull request closed without merging**
