### PR TITLE
Improvement: method 'resize' is now  available publicly

### PR DESCRIPTION
**Pull request by SamyCookie**
I need to have an access to the 'resize' method outside. So, I made it public.

### CODE REVIEW

**Comment by mistic100** [comment]
There are some mistakes here, it works only because you are lucky.

1. When the resize method is created with throttle, "this" does not exist, because this pare of the code is not an instance, it's only the creation of the class/prototype. But it works because there is a "security" on line 480 (`context || that`)
Anyway the resize method itself should not be throttled.

2. Line 163 I don't even understand where "data" come from...

So I propose the change lines 162-164 into
```js
$(window).on('resize', throttle(this.resize, 50, this));
```
And remove the throttling when defining "resize".

PS: watch out your indentation

**Comment by SamyCookie** [comment]
1) I am not very confortable with the 'throttle' method so I made the necessary changes you described
2) https://api.jquery.com/event.data/
I sometimes use it to avoid creating an external new variable.
```javascript
$(foo).on('click', this, function(evt) {
  evt.data.something();
};
```
instead
```javascript
var self = this;
$(foo).on('click', function() {
  self.something();
};
```
I prefer to write the first example, even if both do the same work.

The commit has been refreshed, please review.

**Comment by SamyCookie** [comment]
Hi, I am using this change and unfortunately I think that the strategy used for "throttle" is wrong.
"throttle" behaviour works fine with autoResize on the main window, but throttling is not used when I call 'resize' by myself. I remade this commit at https://github.com/SamyCookie/jQCloud/commit/21f7002e77d1b8cb3ca4ec8d43f3e5941778bd37?w=1. @mistic100 What do you think of this ?

**Comment by mistic100** [comment]
As I said in my previous post, I think it's a bad idea to have a method always throttled, if you need it to be throttled, do it yourself (duplicate the throttle method in your own codebase).

**Comment by SamyCookie** [comment]
Ok then, I'll do that. Thanks !

**Pull request merged**
